name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release Asset
      id: create_release_asset
      run: |
        mvn clean package
        jar_name=$(ls target/*.jar)
        echo "::set-output name=jar_name::$jar_name"

    - name: Upload Release Asset
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.create_release_asset.outputs.jar_name }}
